language: node_js
node_js:
  - "8"
dist: trusty
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script:
  - sleep 10
  - npm run start &
  - sleep 3
  - npm run test
