language: node_js
node_js:
  - "8"
dist: trusty
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run test
notifications:
  email:
    recipients:
      - sung.yi.developer@gmail.com
    on_success: always
    on_failure: always
